from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    dashboard,
    lesson_1,
    lesson_2,
    lesson_3,
    lesson_4,
    lesson_5,
    lesson_6,
    lesson_7,
    lesson_8,
    lesson_9,
    lesson_10,
    lesson_11,
    lesson_12,
    lesson_13,
    lesson_14,
    lesson_15,
    lesson_16,
    lesson_17,
    lesson_review_1,
    lesson_review_2,
    lesson_review_3,
    lesson_review_4,
    lesson_review_5,
    lesson_review_6,
    lesson_review_7,
    activity_review_1,
    activity_review_2,
    activity_review_3,
    activity_review_4,
    activity_review_5,
    quiz_view,
    register,
    login_view,
    logout_view,
    save_quiz_result,
    profile_view,
    game_puzzle,
    game_memory,
    game_map_view,
    game_rpg_view,
    staff_dashboard,
    staff_student_detail,
    ai_tutor,
    ai_tutor_chat,
    ai_tutor_tts,
    activity_isabelle_chat,
    activity_review_6,
    activity_review_7,
    activity_review_8,
    activity_review_9,
    activity_review_10,
    activity_review_11,
    activity_review_12,
    activity_conversation_2,
    update_mastery,
    game_wordsearch,
)

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("ai-tutor/", ai_tutor, name="ai_tutor"),
    path("ai-tutor/chat/", ai_tutor_chat, name="ai_tutor_chat"),
    path("ai-tutor/tts/", ai_tutor_tts, name="ai_tutor_tts"),
    path("lesson/1/", lesson_1, name="lesson_1"),
    path("lesson/2/", lesson_2, name="lesson_2"),
    path("lesson/3/", lesson_3, name="lesson_3"),
    path("lesson/4/", lesson_4, name="lesson_4"),
    path("lesson/5/", lesson_5, name="lesson_5"),
    path("lesson/6/", lesson_6, name="lesson_6"),
    path("lesson/7/", lesson_7, name="lesson_7"),
    path("lesson/8/", lesson_8, name="lesson_8"),
    path("lesson/9/", lesson_9, name="lesson_9"),
    path("lesson/10/", lesson_10, name="lesson_10"),
    path("lesson/11/", lesson_11, name="lesson_11"),
    path("lesson/12/", lesson_12, name="lesson_12"),
    path("lesson/13/", lesson_13, name="lesson_13"),
    path("lesson/14/", lesson_14, name="lesson_14"),
    path("lesson/15/", lesson_15, name="lesson_15"),
    path("lesson/16/", lesson_16, name="lesson_16"),
    path("lesson/17/", lesson_17, name="lesson_17"),
    path("lesson/review/1/", lesson_review_1, name="lesson_review_1"),
    path("lesson/review/2/", lesson_review_2, name="lesson_review_2"),
    path("lesson/review/3/", lesson_review_3, name="lesson_review_3"),
    path("lesson/review/4/", lesson_review_4, name="lesson_review_4"),
    path("lesson/review/5/", lesson_review_5, name="lesson_review_5"),
    path("lesson/review/6/", lesson_review_6, name="lesson_review_6"),
    path("lesson/review/7/", lesson_review_7, name="lesson_review_7"),
    path("activity/review/1/", activity_review_1, name="activity_review_1"),
    path("activity/review/2/", activity_review_2, name="activity_review_2"),
    path("activity/review/3/", activity_review_3, name="activity_review_3"),
    path("activity/review/4/", activity_review_4, name="activity_review_4"),
    path("activity/review/5/", activity_review_5, name="activity_review_5"),
    path("activity/review/6/", activity_review_6, name="activity_review_6"),
    path("activity/review/7/", activity_review_7, name="activity_review_7"),
    path("activity/review/8/", activity_review_8, name="activity_review_8"),
    path("activity/review/9/", activity_review_9, name="activity_review_9"),
    path("activity/review/10/", activity_review_10, name="activity_review_10"),
    path("activity/review/11/", activity_review_11, name="activity_review_11"),
    path("activity/review/12/", activity_review_12, name="activity_review_12"),
    path("activity/conversation-2/", activity_conversation_2, name="activity_conversation_2"),
    path("activity/isabelle-chat/", activity_isabelle_chat, name="activity_isabelle_chat"),
    path("quiz/", quiz_view, name="quiz"),
    path("register/", register, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("api/save-quiz/", save_quiz_result, name="save_quiz_result"),
    path("api/update-mastery/", update_mastery, name="update_mastery"),
    path("profile/", profile_view, name="profile"),
    path("game/puzzle/", game_puzzle, name="game_puzzle"),
    path("game/memory/", game_memory, name="game_memory"),
    path("game/map/", game_map_view, name="game_map"),
    path("game/rpg/", game_rpg_view, name="game_rpg"),
    path("game/wordsearch/", game_wordsearch, name="game_wordsearch"),
    path("game/rpg/<int:world_id>/", game_rpg_view, name="game_rpg_level"),
    path("staff/dashboard/", staff_dashboard, name="staff_dashboard"),
    path(
        "staff/student/<int:user_id>/",
        staff_student_detail,
        name="staff_student_detail",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]
